---
# tasks file for mariadb

 - name: TP2 - MariaDB - Instalando MariaDB
   become: yes
   
   apt: name={{ item }} state=present
   with_items:
   - mariadb-server
   - mariadb-client
   - python3-mysqldb
   - python3-pymysql

 - name: TP2 - Mariadb - Iniciando serviço
   service:
    name: mariadb
    enabled: yes
    state: started

    # - name: MariaDB - Definindo senha root 
    #  mysql_user:
           #    name: root
           #  host: localhost
           # password: 'abc,123'
           # check_implicit_admin: yes
           # login_user: root
           # login_password: 'abc,123'
           #    priv: '*.*:ALL'
           #    state: present

 - name: MariaDB - Criar Base de Dados 
   mysql_db: 
    name: glpi
    state: present

    # - name: Create `/root/.my.cnf`  with root password credentials
    #   template:
    #     src:  my.cnf.j2
    #     dest: /root/.my.cnf
    #    owner: root
    # mode: 0600
    # become: yes
